### ISSUE TITLE
scripts/generate-icon-font: build script fails

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#1818]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

```
npx -p @db-ui/foundations generate-icon-fonts --src ./my-path-to/icons --fontName my-name
```

produces the following error:

```
Error: Cannot find module 'oslllo-svg-fixer'
Require stack:
- /node_modules/@db-ui/foundations/build/scripts/generate-icon-fonts/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at scripts/clean-icons/index.js (/node_modules/@db-ui/foundations/build/scripts/generate-icon-fonts/index.js:44:20)
    at __require (/node_modules/@db-ui/foundations/build/scripts/generate-icon-fonts/index.js:7:50)
    at Object.<anonymous> (/node_modules/@db-ui/foundations/build/scripts/generate-icon-fonts/index.js:224:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/node_modules/@db-ui/foundations/build/scripts/generate-icon-fonts/index.js'
  ]
}

Node.js v18.17.1
```

### Expected Behaviour

No error when building Iconfont

### Browser version

None

**Comment by nmerget** [comment]
Should be solved with standalone package: https://github.com/db-ui/gif
